# GoReleaser configuration for sqs-redrive
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: sqs-redrive
    main: .
    binary: sqs-redrive
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildTime={{.Date}}

archives:
  - id: sqs-redrive
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: dalpark
    name: sqs-redrive
  draft: false
  prerelease: auto
  mode: append
  footer: |
    ## Installation

    **macOS (Apple Silicon)**
    ```bash
    curl -Lo sqs-redrive https://github.com/dalpark/sqs-redrive/releases/download/{{ .Tag }}/sqs-redrive_{{ .Version }}_darwin_arm64.tar.gz
    tar xzf sqs-redrive_{{ .Version }}_darwin_arm64.tar.gz
    chmod +x sqs-redrive
    sudo mv sqs-redrive /usr/local/bin/
    ```

    **Linux (amd64)**
    ```bash
    curl -Lo sqs-redrive.tar.gz https://github.com/dalpark/sqs-redrive/releases/download/{{ .Tag }}/sqs-redrive_{{ .Version }}_linux_amd64.tar.gz
    tar xzf sqs-redrive.tar.gz
    chmod +x sqs-redrive
    sudo mv sqs-redrive /usr/local/bin/
    ```

brews:
  - repository:
      owner: dalpark
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/dalpark/sqs-redrive
    description: AWS SQS Dead Letter Queue redrive CLI tool
    license: MIT
    install: |
      bin.install "sqs-redrive"
    test: |
      system "#{bin}/sqs-redrive", "--help"
